version: '3'
services:
  datascience-notebook:
    image: jupyter/datascience-notebook
    volumes:
      - ./src:/home/jovyan/work
      - ./src/data:/home/jovyan/work/datasets
      - python-modules:/home/jovyan/work/modules
      # - ${LOCAL_SSL_CERTS}:/etc/ssl/notebook
    ports:
      - 8888:8888
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    container_name: jupyter_notebook
    command: "start-notebook.sh --NotebookApp.password='${ACCESS_TOKEN}'"
volumes:
  python-modules:
    driver: local
